# General
n_particles: 1
likelihood_sigma: 0.5 # unused

data:
  salt_prob: 0.0
  awgn_std: 0.1
  image_shape: [28, 28]
  observation_fn: null
sample_dt: 0.02

# prior: null
initial_state: [0.0, 35.0] # mu, sigma (TODO: is this used?)

model: encoder
experiment: lorenz

sequence_length: 8
batch_size: 32
nr_of_sequences: 1024

val_sequence_length: 128
val_batch_size: 32
val_nr_of_sequences: 32 # == val_batch_size
# wandb:
#   project: dpf
#   entity: wessel

save_path: "{output_dir}/dpf/{experiment}/{timestamp}-{model}"
checkpoint: preset:encoder_lorenz_awgn

validation:
  visualize_idx: null
  enable_compute_elbo: False
  dump_results: False
  enable_test_transition_model: False
n_val_epochs: 20