[tool.poetry]
name = "vsmc"
version = "0.1.0"
description = ""
authors = ["Wessel van Nierop <40076995+wesselvannierop@users.noreply.github.com>"]
readme = "README.md"
packages = [
    { include = "vsmc" },
    { include = "usbmd" },
]


[tool.poetry.dependencies]
python = "^3.10"
albumentations = "^1.4"
wandb = ">=0.16, ^0"
torchmetrics = "^1.3"
"ax-platform" = "^0.4"
SimpleITK = "^2.3"
ipympl = "^0.9"
ipykernel = "^6.29"
huggingface_hub = { version = ">=0.22, ^0", extras = ["cli"] }
pathspec = "^0.12"
keras = "^3.4"
# keras==3.6 produces a bug that will fail model.fit after one epoch in graph mode.

[tool.poetry.group.dev.dependencies]
pytest = "^8.1"
pylint = "^3.1"

[tool.poetry.group.torch]
optional = true

# Torch is temporarily on CPU because of CUDA mismatch
[tool.poetry.group.torch.dependencies]
torch = { version = "^2.2", source = "torch-cpu" }
torchvision = { version = "*", source = "torch-cpu" } # any version because torch version handles this

[tool.poetry.group.tensorflow]
optional = true

[tool.poetry.group.tensorflow.dependencies]
tensorflow = { version = "^2.16", extras = ["and-cuda"] }
"tensorflow-probability" = "^0"
"tf-keras" = "^2.16"
"keras-cv" = "^0.9"

[tool.poetry.group.jax]
optional = true

[tool.poetry.group.jax.dependencies]
jax = { version = "^0.4", extras = ["cuda12"] }

[[tool.poetry.source]]
name = "torch-cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
