data:
  salt_prob: 0.0
  awgn_std: 0.1
  image_shape: [28, 28]
  observation_fn: null
  observation_fn_kwargs:
    block_size: 4
    p: 0.1

sample_dt: 0.02

observation_model:
  sigma: 0.1

dpf:
  n_particles: 1
  enable_compute_elbo: True
  dump_results: False
  initial_state: ["true", 1.0] # mu, sigma

transition:
  learn: False
  sigma: 0.5
evolution_model: velocity

sample_mean: True

model: ekpf # bootstrap, learned, ekpf
experiment: lorenz

save_path: "results/{experiment}/{timestamp}-{model}"