data:
  salt_prob: 0.0
  awgn_std: 0.1
  image_shape: [28, 28]
  observation_fn: mask
  observation_fn_kwargs:
    block_size: 4
    p: 0.5

sample_dt: 0.02

dpf:
  initial_state: [0.0, 35.0] # mu, sigma
  n_particles: 1
  enable_compute_elbo: False
  dump_results: False
  enable_test_transition_model: False

model: encoder
experiment: lorenz

save_path: "results/{experiment}/{timestamp}-{model}"
checkpoint: preset:encoder_lorenz_partial_observations
