data:
  salt_prob: 0.0
  awgn_std: 0.1
  image_shape: [28, 28]
  observation_fn: null

sample_dt: 0.02

dpf:
  n_particles: 1
  initial_state: [0.0, 35.0] # mu, sigma
  enable_compute_elbo: False
  dump_results: False
  enable_test_transition_model: False

model: encoder
experiment: lorenz

save_path: "results/{experiment}/{timestamp}-{model}"
checkpoint: preset:encoder_lorenz_awgn
