[tool.poetry]
name = "usbmd"
version = "0.1.0"
authors = [
    "Wessel van Nierop <w.l.v.nierop@tue.nl>",
]

[tool.poetry.dependencies]
python = "^3.10"
keras = "^3.6"
numpy = "^1"
pyyaml = "^6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"